### PR TITLE
Add the tree shaking RFC

### PR DESCRIPTION
**Pull request by matthewp**
[Rendered](https://github.com/stealjs/rfcs/blob/tree-shaking/text/tree-shaking.md)

### CODE REVIEW

**Comment by matthewp** [comment]
Got a note offline to add a bit more on finding unused exports.

**Comment by frank-dspeed** [comment]
@matthewp i see a other problem not handled what if i plan to use dynmaic something that i expect exportet? 
For example i require underscore and later some function in my consumer code wants to use that dynamic and expects that all  methods are use able? we need a tree shake ignore formart for the package.json glob or object based is the question if we would supply path info somehow like in my tar example we could go with glob i think else we need to solve that on package name?

**Comment by matthewp** [comment]
@frank-dspeed If a module is dynamically imported then it should not be tree shaken. I'll update the RFC with that information.

**Comment by matthewp** [comment]
This RFC is entering final comment period. It will be merged in 7 days.

**Comment by matthewp** [comment]
Waited too long, this is being merged 🎸

**Pull request merged**
